arb-dir: lib/l10n
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart
output-dir: .dart_tool/flutter_gen/gen_l10n
untranslated-messages-file: .dart_tool/flutter_gen/untranslated_messages.json
