class CountryCurrency {
  final String name;
  final String currencyCode;

  const CountryCurrency({
    required this.name,
    required this.currencyCode,
  });
}

const allCountries = <CountryCurrency>[
  CountryCurrency(name: 'Afghanistan', currencyCode: 'AFN'),
  CountryCurrency(name: 'Albania', currencyCode: 'ALL'),
  CountryCurrency(name: 'Algeria', currencyCode: 'DZD'),
  CountryCurrency(name: 'Andorra', currencyCode: 'EUR'),
  CountryCurrency(name: 'Angola', currencyCode: 'AOA'),
  CountryCurrency(name: 'Antigua and Barbuda', currencyCode: 'XCD'),
  CountryCurrency(name: 'Argentina', currencyCode: 'ARS'),
  CountryCurrency(name: 'Armenia', currencyCode: 'AMD'),
  CountryCurrency(name: 'Australia', currencyCode: 'AUD'),
  CountryCurrency(name: 'Austria', currencyCode: 'EUR'),
  CountryCurrency(name: 'Azerbaijan', currencyCode: 'AZN'),
  CountryCurrency(name: 'Bahamas', currencyCode: 'BSD'),
  CountryCurrency(name: 'Bahrain', currencyCode: 'BHD'),
  CountryCurrency(name: 'Bangladesh', currencyCode: 'BDT'),
  CountryCurrency(name: 'Barbados', currencyCode: 'BBD'),
  CountryCurrency(name: 'Belarus', currencyCode: 'BYN'),
  CountryCurrency(name: 'Belgium', currencyCode: 'EUR'),
  CountryCurrency(name: 'Belize', currencyCode: 'BZD'),
  CountryCurrency(name: 'Benin', currencyCode: 'XOF'),
  CountryCurrency(name: 'Bhutan', currencyCode: 'BTN'),
  CountryCurrency(name: 'Bolivia', currencyCode: 'BOB'),
  CountryCurrency(name: 'Bosnia and Herzegovina', currencyCode: 'BAM'),
  CountryCurrency(name: 'Botswana', currencyCode: 'BWP'),
  CountryCurrency(name: 'Brazil', currencyCode: 'BRL'),
  CountryCurrency(name: 'Brunei', currencyCode: 'BND'),
  CountryCurrency(name: 'Bulgaria', currencyCode: 'BGN'),
  CountryCurrency(name: 'Burkina Faso', currencyCode: 'XOF'),
  CountryCurrency(name: 'Burundi', currencyCode: 'BIF'),
  CountryCurrency(name: 'Cabo Verde', currencyCode: 'CVE'),
  CountryCurrency(name: 'Cambodia', currencyCode: 'KHR'),
  CountryCurrency(name: 'Cameroon', currencyCode: 'XAF'),
  CountryCurrency(name: 'Canada', currencyCode: 'CAD'),
  CountryCurrency(name: 'Central African Republic', currencyCode: 'XAF'),
  CountryCurrency(name: 'Chad', currencyCode: 'XAF'),
  CountryCurrency(name: 'Chile', currencyCode: 'CLP'),
  CountryCurrency(name: 'China', currencyCode: 'CNY'),
  CountryCurrency(name: 'Colombia', currencyCode: 'COP'),
  CountryCurrency(name: 'Comoros', currencyCode: 'KMF'),
  CountryCurrency(name: 'Congo DR', currencyCode: 'CDF'),
  CountryCurrency(name: 'Congo Republic', currencyCode: 'XAF'),
  CountryCurrency(name: 'Costa Rica', currencyCode: 'CRC'),
  CountryCurrency(name: "Cote d'Ivoire", currencyCode: 'XOF'),
  CountryCurrency(name: 'Croatia', currencyCode: 'EUR'),
  CountryCurrency(name: 'Cuba', currencyCode: 'CUP'),
  CountryCurrency(name: 'Cyprus', currencyCode: 'EUR'),
  CountryCurrency(name: 'Czech Republic', currencyCode: 'CZK'),
  CountryCurrency(name: 'Denmark', currencyCode: 'DKK'),
  CountryCurrency(name: 'Djibouti', currencyCode: 'DJF'),
  CountryCurrency(name: 'Dominica', currencyCode: 'XCD'),
  CountryCurrency(name: 'Dominican Republic', currencyCode: 'DOP'),
  CountryCurrency(name: 'Ecuador', currencyCode: 'USD'),
  CountryCurrency(name: 'Egypt', currencyCode: 'EGP'),
  CountryCurrency(name: 'El Salvador', currencyCode: 'USD'),
  CountryCurrency(name: 'Equatorial Guinea', currencyCode: 'XAF'),
  CountryCurrency(name: 'Eritrea', currencyCode: 'ERN'),
  CountryCurrency(name: 'Estonia', currencyCode: 'EUR'),
  CountryCurrency(name: 'Eswatini', currencyCode: 'SZL'),
  CountryCurrency(name: 'Ethiopia', currencyCode: 'ETB'),
  CountryCurrency(name: 'Fiji', currencyCode: 'FJD'),
  CountryCurrency(name: 'Finland', currencyCode: 'EUR'),
  CountryCurrency(name: 'France', currencyCode: 'EUR'),
  CountryCurrency(name: 'Gabon', currencyCode: 'XAF'),
  CountryCurrency(name: 'Gambia', currencyCode: 'GMD'),
  CountryCurrency(name: 'Georgia', currencyCode: 'GEL'),
  CountryCurrency(name: 'Germany', currencyCode: 'EUR'),
  CountryCurrency(name: 'Ghana', currencyCode: 'GHS'),
  CountryCurrency(name: 'Greece', currencyCode: 'EUR'),
  CountryCurrency(name: 'Grenada', currencyCode: 'XCD'),
  CountryCurrency(name: 'Guatemala', currencyCode: 'GTQ'),
  CountryCurrency(name: 'Guinea', currencyCode: 'GNF'),
  CountryCurrency(name: 'Guinea-Bissau', currencyCode: 'XOF'),
  CountryCurrency(name: 'Guyana', currencyCode: 'GYD'),
  CountryCurrency(name: 'Haiti', currencyCode: 'HTG'),
  CountryCurrency(name: 'Honduras', currencyCode: 'HNL'),
  CountryCurrency(name: 'Hungary', currencyCode: 'HUF'),
  CountryCurrency(name: 'Iceland', currencyCode: 'ISK'),
  CountryCurrency(name: 'India', currencyCode: 'INR'),
  CountryCurrency(name: 'Indonesia', currencyCode: 'IDR'),
  CountryCurrency(name: 'Iran', currencyCode: 'IRR'),
  CountryCurrency(name: 'Iraq', currencyCode: 'IQD'),
  CountryCurrency(name: 'Ireland', currencyCode: 'EUR'),
  CountryCurrency(name: 'Israel', currencyCode: 'ILS'),
  CountryCurrency(name: 'Italy', currencyCode: 'EUR'),
  CountryCurrency(name: 'Jamaica', currencyCode: 'JMD'),
  CountryCurrency(name: 'Japan', currencyCode: 'JPY'),
  CountryCurrency(name: 'Jordan', currencyCode: 'JOD'),
  CountryCurrency(name: 'Kazakhstan', currencyCode: 'KZT'),
  CountryCurrency(name: 'Kenya', currencyCode: 'KES'),
  CountryCurrency(name: 'Kiribati', currencyCode: 'AUD'),
  CountryCurrency(name: 'Korea North', currencyCode: 'KPW'),
  CountryCurrency(name: 'Korea South', currencyCode: 'KRW'),
  CountryCurrency(name: 'Kosovo', currencyCode: 'EUR'),
  CountryCurrency(name: 'Kuwait', currencyCode: 'KWD'),
  CountryCurrency(name: 'Kyrgyzstan', currencyCode: 'KGS'),
  CountryCurrency(name: 'Laos', currencyCode: 'LAK'),
  CountryCurrency(name: 'Latvia', currencyCode: 'EUR'),
  CountryCurrency(name: 'Lebanon', currencyCode: 'LBP'),
  CountryCurrency(name: 'Lesotho', currencyCode: 'LSL'),
  CountryCurrency(name: 'Liberia', currencyCode: 'LRD'),
  CountryCurrency(name: 'Libya', currencyCode: 'LYD'),
  CountryCurrency(name: 'Liechtenstein', currencyCode: 'CHF'),
  CountryCurrency(name: 'Lithuania', currencyCode: 'EUR'),
  CountryCurrency(name: 'Luxembourg', currencyCode: 'EUR'),
  CountryCurrency(name: 'Madagascar', currencyCode: 'MGA'),
  CountryCurrency(name: 'Malawi', currencyCode: 'MWK'),
  CountryCurrency(name: 'Malaysia', currencyCode: 'MYR'),
  CountryCurrency(name: 'Maldives', currencyCode: 'MVR'),
  CountryCurrency(name: 'Mali', currencyCode: 'XOF'),
  CountryCurrency(name: 'Malta', currencyCode: 'EUR'),
  CountryCurrency(name: 'Marshall Islands', currencyCode: 'USD'),
  CountryCurrency(name: 'Mauritania', currencyCode: 'MRU'),
  CountryCurrency(name: 'Mauritius', currencyCode: 'MUR'),
  CountryCurrency(name: 'Mexico', currencyCode: 'MXN'),
  CountryCurrency(name: 'Micronesia', currencyCode: 'USD'),
  CountryCurrency(name: 'Moldova', currencyCode: 'MDL'),
  CountryCurrency(name: 'Monaco', currencyCode: 'EUR'),
  CountryCurrency(name: 'Mongolia', currencyCode: 'MNT'),
  CountryCurrency(name: 'Montenegro', currencyCode: 'EUR'),
  CountryCurrency(name: 'Morocco', currencyCode: 'MAD'),
  CountryCurrency(name: 'Mozambique', currencyCode: 'MZN'),
  CountryCurrency(name: 'Myanmar', currencyCode: 'MMK'),
  CountryCurrency(name: 'Namibia', currencyCode: 'NAD'),
  CountryCurrency(name: 'Nauru', currencyCode: 'AUD'),
  CountryCurrency(name: 'Nepal', currencyCode: 'NPR'),
  CountryCurrency(name: 'Netherlands', currencyCode: 'EUR'),
  CountryCurrency(name: 'New Zealand', currencyCode: 'NZD'),
  CountryCurrency(name: 'Nicaragua', currencyCode: 'NIO'),
  CountryCurrency(name: 'Niger', currencyCode: 'XOF'),
  CountryCurrency(name: 'Nigeria', currencyCode: 'NGN'),
  CountryCurrency(name: 'North Macedonia', currencyCode: 'MKD'),
  CountryCurrency(name: 'Norway', currencyCode: 'NOK'),
  CountryCurrency(name: 'Oman', currencyCode: 'OMR'),
  CountryCurrency(name: 'Pakistan', currencyCode: 'PKR'),
  CountryCurrency(name: 'Palau', currencyCode: 'USD'),
  CountryCurrency(name: 'Palestine', currencyCode: 'ILS'),
  CountryCurrency(name: 'Panama', currencyCode: 'PAB'),
  CountryCurrency(name: 'Papua New Guinea', currencyCode: 'PGK'),
  CountryCurrency(name: 'Paraguay', currencyCode: 'PYG'),
  CountryCurrency(name: 'Peru', currencyCode: 'PEN'),
  CountryCurrency(name: 'Philippines', currencyCode: 'PHP'),
  CountryCurrency(name: 'Poland', currencyCode: 'PLN'),
  CountryCurrency(name: 'Portugal', currencyCode: 'EUR'),
  CountryCurrency(name: 'Qatar', currencyCode: 'QAR'),
  CountryCurrency(name: 'Romania', currencyCode: 'RON'),
  CountryCurrency(name: 'Russia', currencyCode: 'RUB'),
  CountryCurrency(name: 'Rwanda', currencyCode: 'RWF'),
  CountryCurrency(name: 'Saint Kitts and Nevis', currencyCode: 'XCD'),
  CountryCurrency(name: 'Saint Lucia', currencyCode: 'XCD'),
  CountryCurrency(name: 'Saint Vincent and the Grenadines', currencyCode: 'XCD'),
  CountryCurrency(name: 'Samoa', currencyCode: 'WST'),
  CountryCurrency(name: 'San Marino', currencyCode: 'EUR'),
  CountryCurrency(name: 'Sao Tome and Principe', currencyCode: 'STN'),
  CountryCurrency(name: 'Saudi Arabia', currencyCode: 'SAR'),
  CountryCurrency(name: 'Senegal', currencyCode: 'XOF'),
  CountryCurrency(name: 'Serbia', currencyCode: 'RSD'),
  CountryCurrency(name: 'Seychelles', currencyCode: 'SCR'),
  CountryCurrency(name: 'Sierra Leone', currencyCode: 'SLE'),
  CountryCurrency(name: 'Singapore', currencyCode: 'SGD'),
  CountryCurrency(name: 'Slovakia', currencyCode: 'EUR'),
  CountryCurrency(name: 'Slovenia', currencyCode: 'EUR'),
  CountryCurrency(name: 'Solomon Islands', currencyCode: 'SBD'),
  CountryCurrency(name: 'Somalia', currencyCode: 'SOS'),
  CountryCurrency(name: 'South Africa', currencyCode: 'ZAR'),
  CountryCurrency(name: 'South Sudan', currencyCode: 'SSP'),
  CountryCurrency(name: 'Spain', currencyCode: 'EUR'),
  CountryCurrency(name: 'Sri Lanka', currencyCode: 'LKR'),
  CountryCurrency(name: 'Sudan', currencyCode: 'SDG'),
  CountryCurrency(name: 'Suriname', currencyCode: 'SRD'),
  CountryCurrency(name: 'Sweden', currencyCode: 'SEK'),
  CountryCurrency(name: 'Switzerland', currencyCode: 'CHF'),
  CountryCurrency(name: 'Syria', currencyCode: 'SYP'),
  CountryCurrency(name: 'Taiwan', currencyCode: 'TWD'),
  CountryCurrency(name: 'Tajikistan', currencyCode: 'TJS'),
  CountryCurrency(name: 'Tanzania', currencyCode: 'TZS'),
  CountryCurrency(name: 'Thailand', currencyCode: 'THB'),
  CountryCurrency(name: 'Timor-Leste', currencyCode: 'USD'),
  CountryCurrency(name: 'Togo', currencyCode: 'XOF'),
  CountryCurrency(name: 'Tonga', currencyCode: 'TOP'),
  CountryCurrency(name: 'Trinidad and Tobago', currencyCode: 'TTD'),
  CountryCurrency(name: 'Tunisia', currencyCode: 'TND'),
  CountryCurrency(name: 'Turkey', currencyCode: 'TRY'),
  CountryCurrency(name: 'Turkmenistan', currencyCode: 'TMT'),
  CountryCurrency(name: 'Tuvalu', currencyCode: 'AUD'),
  CountryCurrency(name: 'Uganda', currencyCode: 'UGX'),
  CountryCurrency(name: 'Ukraine', currencyCode: 'UAH'),
  CountryCurrency(name: 'United Arab Emirates', currencyCode: 'AED'),
  CountryCurrency(name: 'United Kingdom', currencyCode: 'GBP'),
  CountryCurrency(name: 'United States', currencyCode: 'USD'),
  CountryCurrency(name: 'Uruguay', currencyCode: 'UYU'),
  CountryCurrency(name: 'Uzbekistan', currencyCode: 'UZS'),
  CountryCurrency(name: 'Vanuatu', currencyCode: 'VUV'),
  CountryCurrency(name: 'Vatican City', currencyCode: 'EUR'),
  CountryCurrency(name: 'Venezuela', currencyCode: 'VES'),
  CountryCurrency(name: 'Vietnam', currencyCode: 'VND'),
  CountryCurrency(name: 'Yemen', currencyCode: 'YER'),
  CountryCurrency(name: 'Zambia', currencyCode: 'ZMW'),
  CountryCurrency(name: 'Zimbabwe', currencyCode: 'USD'),
];

CountryCurrency? findCountryByName(String value) {
  final normalized = value.trim().toLowerCase();
  for (final country in allCountries) {
    if (country.name.toLowerCase() == normalized) {
      return country;
    }
  }
  return null;
}
