import '../models/recurring_payment.dart';
import '../models/user_settings.dart';

final mockSettings = UserSettings.defaults().copyWith(onboardingCompleted: true);

final mockPayments = <RecurringPayment>[
  RecurringPayment(
    id: '1',
    userId: 'mock-user',
    name: 'Netflix',
    amount: 19.99,
    currency: 'USD',
    category: PaymentCategory.subscription,
    frequency: PaymentFrequency.monthly,
    nextDueDate: DateTime.now().add(const Duration(days: 2)),
    reminderEnabled: true,
    reminderTiming: ReminderTiming.oneDayBefore,
    status: PaymentStatus.active,
    isTrial: false,
    trialEndDate: null,
    trialReminderEnabled: false,
    convertsToPaidAmount: null,
    trialNotes: '',
    cancellationUrl: 'https://www.netflix.com/cancelplan',
    cancellationNotes: 'Cancel from Account > Membership.',
    cancellationStatus: CancellationStatus.active,
    cancelledAt: null,
    iconKey: 'movie',
    priceHistory: const [],
    createdAt: DateTime.now().subtract(const Duration(days: 150)),
    updatedAt: DateTime.now().subtract(const Duration(days: 10)),
  ),
  RecurringPayment(
    id: '2',
    userId: 'mock-user',
    name: 'Spotify',
    amount: 17.99,
    currency: 'USD',
    category: PaymentCategory.subscription,
    frequency: PaymentFrequency.monthly,
    nextDueDate: DateTime.now().add(const Duration(days: 6)),
    reminderEnabled: true,
    reminderTiming: ReminderTiming.threeDaysBefore,
    status: PaymentStatus.active,
    isTrial: false,
    trialEndDate: null,
    trialReminderEnabled: false,
    convertsToPaidAmount: null,
    trialNotes: '',
    cancellationUrl: 'https://www.spotify.com/account/subscription',
    cancellationNotes: 'Can downgrade to free plan.',
    cancellationStatus: CancellationStatus.considering,
    cancelledAt: null,
    iconKey: 'music',
    priceHistory: const [],
    createdAt: DateTime.now().subtract(const Duration(days: 120)),
    updatedAt: DateTime.now().subtract(const Duration(days: 7)),
  ),
  RecurringPayment(
    id: '3',
    userId: 'mock-user',
    name: 'Adobe Creative Cloud Trial',
    amount: 0,
    currency: 'USD',
    category: PaymentCategory.subscription,
    frequency: PaymentFrequency.monthly,
    nextDueDate: DateTime.now().add(const Duration(days: 10)),
    reminderEnabled: true,
    reminderTiming: ReminderTiming.threeDaysBefore,
    status: PaymentStatus.active,
    isTrial: true,
    trialEndDate: DateTime.now().add(const Duration(days: 5)),
    trialReminderEnabled: true,
    convertsToPaidAmount: 59.99,
    trialNotes: 'High chance of forgetting this one.',
    cancellationUrl: 'https://account.adobe.com',
    cancellationNotes: 'Check early cancellation terms first.',
    cancellationStatus: CancellationStatus.considering,
    cancelledAt: null,
    iconKey: 'bolt',
    priceHistory: const [],
    createdAt: DateTime.now().subtract(const Duration(days: 5)),
    updatedAt: DateTime.now().subtract(const Duration(days: 1)),
  ),
  RecurringPayment(
    id: '4',
    userId: 'mock-user',
    name: 'Apartment Rent',
    amount: 1450,
    currency: 'USD',
    category: PaymentCategory.rent,
    frequency: PaymentFrequency.monthly,
    nextDueDate: DateTime.now().add(const Duration(days: 3)),
    reminderEnabled: true,
    reminderTiming: ReminderTiming.sameDay,
    status: PaymentStatus.active,
    isTrial: false,
    trialEndDate: null,
    trialReminderEnabled: false,
    convertsToPaidAmount: null,
    trialNotes: '',
    cancellationUrl: '',
    cancellationNotes: '',
    cancellationStatus: CancellationStatus.active,
    cancelledAt: null,
    iconKey: 'home',
    priceHistory: const [],
    createdAt: DateTime.now().subtract(const Duration(days: 300)),
    updatedAt: DateTime.now().subtract(const Duration(days: 21)),
  ),
];
